name: CI

on: push

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "16"
      - run: yarn
      - run: yarn lint
